### ISSUE TITLE
Allow custom session key generators

### ISSUE THREAD

**Issue by Xeizzen** [qbeon/webwire-go#10]
Currently, there's no way to implement your own session key generator which is rather restrictive. It'd be nice to have the possibility to provide your own generator or use the built-in generator by default.

**Comment by romshark** [comment]
As of [commit #a1ec834](https://github.com/qbeon/webwire-go/commit/a1ec8347c8f6c902ca48ff41138a309ced467afd) support for custom session key generators is fully implemented and tested.

A custom key generator can now be passed to the new server hook `OnSessionKeyGeneration`.

Even though it's possible now to define custom session key generators you **shouldn't** use this hook, unless you really know what you do as this could compromise security if implemented improperly!
