### ISSUE TITLE
Autoconnect in the background

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#12]
Issue #11 already covers the autoconnect feature but misses one important case:

When the client connects to the server just to listen to server-side signals - the connection could get lost at some point (due to a server reboot for example) and the user-code will assume, that there's just nothing happening on the server, but in reality the server just won't send the signals due to the client being disconnected whole the time.
In such a case it's very important for the client to try to reconnect in the background as soon as the connection is lost to ensure maximum uptime.

**Comment by romshark** [comment]
I've successfuly implemented this feature in the [background-autoconnect](https://github.com/qbeon/webwire-go/tree/background-autoconnect) branch, though faced a potential bug in the underlying websockets implementation. Getting a **1002 (protocol error): unexpected reserved bits 0x50** causing the server to close the reestablished connection for unknown reasons. Seems like some invalid state is left somewhere in the underlying websocket dialer causing the reestablished connection to send corrupted messages. I've posted an [issue about it](https://github.com/gorilla/websocket/issues/366).

**Comment by romshark** [comment]
As [garyburd](https://github.com/garyburd) denoted in the [issue](https://github.com/gorilla/websocket/issues/366), the problem is caused by a race condition. I realized the client doesn't neither reuse nor kill the socket-reading goroutine that is created in the `client.connect` method, a second reader is spawned on reconnection which finally causes unsynchronized concurrent access to the sockets `ReadMessage` method, gonna fix that now.

**Comment by romshark** [comment]
As of [commit #f0ab6a3](https://github.com/qbeon/webwire-go/commit/0922a5c94d14873ecc9210c26a6ec6fb430682a2) the client will automatically try to connect in the background whenever the connection to the server is lost, as well as when the client instance is created by the constructor method `wwrclt.NewClient`, when the autoconnect option is enabled.

When connection loss is detected, the client will create a dedicated reconnection goroutine that's suspended when the connection is reestablished. Subsequent autoconnection attempts will wait for this goroutine to complete and possibly timeout. This way resource usage and network load is minimized.
