### ISSUE TITLE
Deferred client-side session destruction

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#16]
When the session is closed by the client offline due a temporarily interrupted connection, then the client will just remove and forget it while it will remain open on the server even when the connection is reestablished.

The client should be made responsible for cleaning up when a session was closed offline. It must remember the session key and request the destruction of the closed sessions as soon as the connection is reestablished, to reduce server-load.

**Comment by romshark** [comment]
I think that this feature would increase code complexity without an actual benefit. A webwire server with sessions enabled will require periodic garbage collection anyway, outdated sessions must be removed by a chron-job or similar.
