### ISSUE TITLE
Use *log.Logger instead of io.Writer for logging

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#19]
Use `*log.Logger` instead of `io.Writer` for logging, it allows the library user to set custom logging flags and prefixes. Currently this is not possible and the [default prefixes](https://github.com/qbeon/webwire-go/blob/9b742162c0eb6716dc7d379b0aaa524eac3e3f0f/server.go#L64) are used like: `WARNING: ` and `ERROR: `, though we'd like to differentiate between error logs produced by webwire and our own code.

**Comment by romshark** [comment]
As of (commit #a12e9d6)[https://github.com/qbeon/webwire-go/commit/a12e9d61b5ed059a3976b565254a7382f9d331cf] `*log.Logger` are now passed as log targets in both the client and the server options.
