### ISSUE TITLE
Listing all connections of a session

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#20]
There's currently no way to list all connections (aka client agents) belonging to a certain session. The only function that comes close to solving this issue is [SessionRegistry.SessionConnections](https://github.com/qbeon/webwire-go/blob/master/sessionRegistry.go#L15) though it returns only the *number* of connections of the given session. Wouldn't it make more sense to return `[]*Client` instead?

**Comment by romshark** [comment]
As of [commit #8f789c0](https://github.com/qbeon/webwire-go/commit/8f789c07c2bd09fd6821bfcb62b7f429b364c045) [server.SessionConnections](https://github.com/qbeon/webwire-go/blob/master/webwireServer.go#L34) returns a list of client agents
