### ISSUE TITLE
Update session relevance

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#24]
Sessions must get a new field "lastUse" of date type to indicate when a particular session was lastly updated. This is important for the session manager to know whether a session is still relevant during garbage collection.

**Comment by romshark** [comment]
As of [commit #cbd6017](https://github.com/qbeon/webwire-go/commit/cbd6017494ae5c423a7e419e2e650bd3d0eb81b3) a new `LastLookup` field is added to the webwire session object. It denotes the last time the session was looked up by the server and should prevent any session garbage collector from deleting active sessions.

### Important Notes
When implementing the `OnSessionLookup` method of the `SessionManager` interface, the library user must now also permanently update the `LastLookup` field of the looked up session (if it's found) setting the current time. This is now mentioned in the documentation of this hook.
