### ISSUE TITLE
Add support for context.Context

### ISSUE THREAD

**Issue by ghost** [qbeon/webwire-go#27]
Add support for cancellation and deadlines through _context.Context_ in methods such as [client.Request](https://github.com/qbeon/webwire-go/blob/db87e43fe9dbbea38cfe0ebdead36d8d0cf07bfc/client/client.go#L165)

**Comment by romshark** [comment]
Yes, this sounds reasonable and must be done.

`context.Context` would also make `client.TimedRequest` obsolete.
