### ISSUE TITLE
Add new constructor function with TLS support

### ISSUE THREAD

**Issue by SevansD** [qbeon/webwire-go#35]
# Server feature request

## Description
For use webwire on https we need to do a lot of action, as in [example](https://github.com/qbeon/webwire-example-postboard/blob/master/server/apisrv/server.go). It will be more convenient to have a constructor that will accept, in addition to the ServerImplementation and ServerOptions, a certificate with a key and listen https connections, like:
```golang
func NewSecureServer(
	implementation ServerImplementation,
	opts ServerOptions,
	certFile,
	keyFile string,
)
```

**Comment by romshark** [comment]
Since [69d04cc](https://github.com/qbeon/webwire-go/commit/69d04ccc60d5006446d3060d49ffe6ecfe3ee93b) webwire now provides a new constructor method: `webwire.NewServerSecure`. The client now also accepts custom TLS configurations.
