### ISSUE TITLE
Use standard error interface in OnRequest hook

### ISSUE THREAD

**Issue by Xeizzen** [qbeon/webwire-go#5]
Currently a custom error type **webwire.Error** is used in the **OnRequest** hook, which is fine but consider using the default Go error interface as this would ease the use of the library. When a non-webwire.Error is returned the transmitted reply error could probably have some default code value.

**Comment by romshark** [comment]
The pull request containing the proposed feature has been accepted and integrated in [this commit](https://github.com/qbeon/webwire-go/commit/dfdb7b3fac89932a5d33d3373f250dcdfa1b1ac4)
